### ISSUE TITLE
Issue with container

### ISSUE THREAD

**Issue by ghost** [martin-georgiev/social-post-bundle#11]
Hi there,

Sorry if this is an obvious answer, but I am getting the following error when I attempt to post a message showing using your demo code:

`Notice: Undefined variable: container`

How do I go about fixing this?

Thanks

**Comment by martin-georgiev** [comment]
`$container` from the example refers to the [Symfony container](https://symfony.com/doc/3.4/service_container.html). A service `social_post` will be registered to it.
You can also instantiate the [core service](https://github.com/martin-georgiev/social-post-bundle/blob/2.0.1/src/MartinGeorgiev/SocialPost/Provider/AllInOne.php) on your own (if you don't use Symfony for example) and this will require some boiler-plate code from your end.

Later this year/Early 2018 I plan to release the core logic as a decoupled package with examples how to integrate into non-symfony projects.

**Comment by ghost** [comment]
Awesome thanks, Got it working!

**Comment by martin-georgiev** [comment]
Perfect! Closing this as seems your question is answered now.
