### ISSUE TITLE
[QUESTION] Providers list + HTML Template message

### ISSUE THREAD

**Issue by christophe-44-27** [martin-georgiev/social-post-bundle#17]
Hi,

Can you provide the list of providers that we can configure into this bundle ? And is it possible to send "html message template" or just "text message" ?

Regards,
Christophe

**Comment by martin-georgiev** [comment]
There are no limitations on the bundle level for HTML messages. However, I'll be very surprised if social networks actually allow such content as this poses a major security risk for them. You can use the bundle for publishing on Facebook pages, Linkedin and Twitter feeds. Configuration for this is in the README.

**Comment by christophe-44-27** [comment]
Do you think that you will be able to add some other providers like Instagram for example ?

And for "html template", yes you are right, and i think that "emoji" will be considered as texte also.

**Comment by martin-georgiev** [comment]
Instagram is definitely considered as the next supported social network. Unfortunately, I can't engage with a release date for this.

**Comment by christophe-44-27** [comment]
No problems, thanks a lot for your answers !
