### ISSUE TITLE
Symfony3.4 Exception

### ISSUE THREAD

**Issue by DeveloperSlope3** [martin-georgiev/social-post-bundle#24]
Hi!

I got this error when installing the latest version of the bundle and I don't know how to solve it

> (1/1) UndefinedMethodException
Attempted to call an undefined method named "getRootNode" of class "Symfony\Component\Config\Definition\Builder\TreeBuilder".

Thanks a lot.
Regards

**Comment by martin-georgiev** [comment]
So I can look in this can you share the full stack trace of the error and the versions of your composer dependencies?

**Comment by DeveloperSlope3** [comment]
Hi Martin!

Here is my composer.json:

`{
    "name": "symfony/framework-standard-edition",
    "license": "MIT",
    "type": "project",
    "description": "The \"Symfony Standard Edition\" distribution",
    "autoload": {
        "psr-0": {
            "": "src/"
        },
        "classmap": [ "app/AppKernel.php", "app/AppCache.php" ]
    },
    "require": {
        "php": "^7",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/orm": "^2.5",
        "incenteev/composer-parameter-handler": "^2.0",
        "sensio/distribution-bundle": "^5.0.19",
        "sensio/framework-extra-bundle": "^5.0.0",
        "symfony/monolog-bundle": "^3.1.0",
        "symfony/polyfill-apcu": "^1.0",
        "symfony/swiftmailer-bundle": "^2.6.4",
        "symfony/symfony": "3.4.*",
        "twig/twig": "^1.0||^2.0",
        "vihuvac/htmlcompressor-bundle": "^1.0",
        "endroid/qr-code-bundle": "^3.3",
        "jms/serializer-bundle": "^2.4",
        "sendgrid/sendgrid": "^7.2",
        "wisembly/elephant.io": "^3.3",
        "beberlei/DoctrineExtensions": "^1.2",
        "guhelski/forecast-php": "^1.1",
        "knplabs/knp-paginator-bundle": "^3.0",
        "rukbat/bitly-bundle": "^0.1.4",
        "elao/error-notifier-bundle": "^1.0",
        "nelmio/api-doc-bundle": "^3.4",
        "friendsofsymfony/rest-bundle": "^2.5",
        "lexik/form-filter-bundle": "^5.0",
        "guzzlehttp/guzzle": "^6.3",
        "friendsofsymfony/jsrouting-bundle": "^2.3",
        "symfony/event-dispatcher": "3.4.*",
        "zendframework/zend-soap": "^2.7",
        "friendsofsymfony/user-bundle": "^2.1",
        "martin-georgiev/social-post-bundle": "^3.0",
        "twig/extensions": "^1.5",
        "knpuniversity/oauth2-client-bundle": "^1.28",
        "league/oauth2-google": "^3.0"
    },
    "require-dev": {
        "sensio/generator-bundle": "^3.0",
        "symfony/phpunit-bridge": "^3.0"
    },
    "scripts": {
        "symfony-scripts": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-install-cmd": [
            "@symfony-scripts"
        ],
        "post-update-cmd": [
            "@symfony-scripts"
        ]
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-bin-dir": "bin",
        "symfony-var-dir": "var",
        "symfony-web-dir": "web",
        "symfony-tests-dir": "tests",
        "symfony-assets-install": "relative",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        },
        "branch-alias": {
            "dev-master": "3.4-dev"
        }
    }
}`

And here is the stack trace:

`(1/1) UndefinedMethodExceptionAttempted to call an undefined method named "getRootNode" of class "Symfony\Component\Config\Definition\Builder\TreeBuilder".
--
in Configuration.php line 21
at Configuration->getConfigTreeBuilder() in Processor.php line 50
at Processor->processConfiguration(object(Configuration), array(array('publish_on' => array('facebook', 'twitter'), 'providers' => array('facebook' => array('app_id' => 'my_app_id', 'app_secret' => 'my_app_secret', 'default_access_token' => 'my_default-access_token', 'page_id' => 'my_page_id', 'enable_beta_mode' => true, 'default_graph_version' => 'v2.8', 'persistent_data_handler' => 'memory', 'pseudo_random_string_generator' => 'openssl', 'http_client_handler' => 'curl'), 'twitter' => array('consumer_key' => 'my_consumer_key', 'consumer_secret' => 'my_consumer_secret', 'access_token' => 'my_access_token', 'access_token_secret' => 'my_access_token_secret'))))) in Extension.php line 96 
at Extension->processConfiguration(object(Configuration), array(array('publish_on' => array('facebook', 'twitter'), 'providers' => array('facebook' => array('app_id' => 'my_app_id', 'app_secret' => 'my_app_secret', 'default_access_token' => 'my_default_access_token', 'page_id' => 'my_page_id', 'enable_beta_mode' => true, 'default_graph_version' => 'v2.8', 'persistent_data_handler' => 'memory', 'pseudo_random_string_generator' => 'openssl', 'http_client_handler' => 'curl'), 'twitter' => array('consumer_key' => 'my_consumer_key', 'consumer_secret' => 'my_costumer-secret', 'access_token' => 'my_access_token', 'access_token_secret' => 'my_access_secret_token'))))) in SocialPostExtension.php line 39
at SocialPostExtension->load(array(array('publish_on' => array('facebook', 'twitter'), 'providers' => array('facebook' => array('app_id' => 'my_app_id', 'app_secret' => 'my_app_secret', 'default_access_token' => 'my_default_access_token', 'page_id' => 'my_page_id', 'enable_beta_mode' => true, 'default_graph_version' => 'v2.8', 'persistent_data_handler' => 'memory', 'pseudo_random_string_generator' => 'openssl', 'http_client_handler' => 'curl'), 'twitter' => array('consumer_key' => 'my_consumer_key', 'consumer_secret' => 'my_consumer_secret', 'access_token' => 'my_access_token', 'access_token_secret' => 'my_access_token_secret')))), object(MergeExtensionConfigurationContainerBuilder))in MergeExtensionConfigurationPass.php line 71
at MergeExtensionConfigurationPass->process(object(ContainerBuilder)) in MergeExtensionConfigurationPass.php line 39
at MergeExtensionConfigurationPass->process(object(ContainerBuilder))in Compiler.php line 141
at Compiler->compile(object(ContainerBuilder))in ContainerBuilder.php line 788
at ContainerBuilder->compile()in Kernel.php line 637
at Kernel->initializeContainer()in Kernel.php line 135
at Kernel->boot()in Kernel.php line 195
at Kernel->handle(object(Request))in app_dev.php line 29`

**Comment by DeveloperSlope3** [comment]
When i clean cache it appears:

> PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\UndefinedMethodException: Attempted to call an undefined method named "getRootNode" of class "Symfony\Component\Config\Definition\Builder\TreeBuilder". in C:\xampp\htdocs\appNextCaddySF3-4\vendor\martin-georgiev\social-post-bundle\src\MartinGeorgiev\SocialPostBundle\DependencyInjection\Configuration.php:21
Stack trace:
#0 C:\xampp\htdocs\appNextCaddySF3-4\vendor\symfony\symfony\src\Symfony\Component\Config\Definition\Processor.php(50): MartinGeorgiev\SocialPostBundle\DependencyInjection\Configuration->getConfigTreeBuilder()
#1 C:\xampp\htdocs\appNextCaddySF3-4\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Extension\Extension.php(96): Symfony\Component\Config\Definition\Processor->processConfiguration(Object(MartinGeorgiev\SocialPostBundle\DependencyInjection\Configuration), Array)
#2 C:\xampp\htdocs\appNextCaddySF3-4\vendor\martin-georgiev\social-post-bundle\src\MartinGeorgiev\SocialPostBundle\DependencyInjection\SocialPostExtension.php(39): Symfon in C:\xampp\htdocs\appNextCaddySF3-4\vendor\martin-georgiev\social-post-bundle\src\MartinGeorgiev\SocialPostBundle\DependencyInjection\Configuration.php on line 21
Fatal error: Uncaught Symfony\Component\Debug\Exception\UndefinedMethodException: Attempted to call an undefined method named "getRootNode" of class "Symfony\Component\Config\Definition\Builder\TreeBuilder". in C:\xampp\htdocs\appNextCaddySF3-4\vendor\martin-georgiev\social-post-bundle\src\MartinGeorgiev\SocialPostBundle\DependencyInjection\Configuration.php:21
Stack trace:
#0 C:\xampp\htdocs\appNextCaddySF3-4\vendor\symfony\symfony\src\Symfony\Component\Config\Definition\Processor.php(50): MartinGeorgiev\SocialPostBundle\DependencyInjection\Configuration->getConfigTreeBuilder()
#1 C:\xampp\htdocs\appNextCaddySF3-4\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Extension\Extension.php(96): Symfony\Component\Config\Definition\Processor->processConfiguration(Object(MartinGeorgiev\SocialPostBundle\DependencyInjection\Configuration), Array)
#2 C:\xampp\htdocs\appNextCaddySF3-4\vendor\martin-georgiev\social-post-bundle\src\MartinGeorgiev\SocialPostBundle\DependencyInjection\SocialPostExtension.php(39): Symfon in C:\xampp\htdocs\appNextCaddySF3-4\vendor\martin-georgiev\social-post-bundle\src\MartinGeorgiev\SocialPostBundle\DependencyInjection\Configuration.php on line 21

**Comment by martin-georgiev** [comment]
@DeveloperSlope3 Thanks for the reported regression. It indeed affected v3.0.1. This is now fixed in v3.0.2. Please upgrade.
