### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by phtmgt** [martin-georgiev/social-post-bundle#4]
Hi Martin,

First of all, great job. Keep it up. Based on our use case I'd like to suggest the following:
Option to disable one or the other (fb/twitter)
Multiple credentials for both (so posts can be submitted to different accounts/pages based on 
Ability to auto-renew facebook token (we were not able to get one with an expiry date more than 2 months into the future).

**Comment by martin-georgiev** [comment]
Do you want to conditionally disable Facebook or Twitter during runtime?


In regards to the Facebook long-living token, Facebook doesn't support non-expiring user access tokens. Instead, you can obtain a permanent page access token. When using such tokens you can act and post as the page itself. This means the post will appear as written by the page itself and not on the name of the administrator of that page. More information about the page access tokens is available in the official [Facebook documentation](https://developers.facebook.com/docs/facebook-login/access-tokens/expiration-and-extension#extendingpagetokens). Some Stackoverflow answers ([here](https://stackoverflow.com/a/21927690/3425372) and [here](https://stackoverflow.com/a/28418469/3425372)) also prove to be helpful.

**Comment by p11v** [comment]
Yes, the idea is that in some cases a user might want to post on one of the social networks only.

**Comment by martin-georgiev** [comment]
A quick workaround for this will be to override the default service configuration of SocialPostBundle.
By default, the bundle comes with two non-public services - `social_post.facebook` and `social_post.twitter`. You need to change them to public, so they are accessible in your controllers. Check the complete default configuration [here](https://github.com/martin-georgiev/social-post-bundle/blob/master/src/MartinGeorgiev/SocialPost/Resources/config/services.yml).
After that you can call `$container->get('social_post.facebook')->publish('your message that will go only to Facebook')`.

More about how to override vendor bundle configuration can be found on [Stackoverflow](http://stackoverflow.com/questions/9627461/how-to-override-a-vendor-bundle-configuration).

I'll add a nicer control for disable functionality in version 2 (that should be out by 1st of June).

**Comment by martin-georgiev** [comment]
Did you manage to generate a long-living Facebook page token?

I've implemented your request for having a way to publish a post only to some networks during runtime. You can use commit [69d7e7a](https://github.com/martin-georgiev/social-post-bundle/commit/69d7e7a00a119a3d956b3db022f884b65424909b) as a reference. If you are in a hurry to benefir from this new functionality, change your composer.json dependency to require exactly that commit id. A breaking change is that you'll have to pass an instance of [`Message`](https://github.com/martin-georgiev/social-post-bundle/blob/1633d4914302422a6eba7dca5bf3512cb604ad36/src/MartinGeorgiev/SocialPost/Provider/Message.php) when you want to [`publish()`](https://github.com/martin-georgiev/social-post-bundle/blob/1633d4914302422a6eba7dca5bf3512cb604ad36/src/MartinGeorgiev/SocialPost/Provider/SocialNetworkPublisher.php).
Detailed documentation will follow lately when v2.0 is ready for release.

**Comment by p11v** [comment]
Not yet, since I am busy with other stuff.

That sounds great. I will try it soon. 

Great job!

**Comment by martin-georgiev** [comment]
This is now released under version 2.0.0
