### ISSUE TITLE
Error when trying to publish on facebook

### ISSUE THREAD

**Issue by josejbarneto** [martin-georgiev/social-post-bundle#9]
Hello, I'm using your bundle to post on Twitter and Facebook, twitter one is working correctly, but when i try to publish on fb im getting this error.
I'm using exactly and only your documentation settings and code

$message = new \MartinGeorgiev\SocialPost\Provider\Message('your test message');
$container->get('social_post')->publish($message);

> Cannot publish message. Last known error was: Cannot publish message. Last known error was: (#200) Posts where the actor is a page cannot also include a target_id
other than EVENT or GROUP

 Thank you.

**Comment by martin-georgiev** [comment]
Sounds like you are not posting to the page's own wall but instead to a user's or another page's wall.
Did you check that the bundle's Facebook configuration values match with your Facebook page?

**Comment by josejbarneto** [comment]
I finally fixed it,

Thank you.

**Comment by martin-georgiev** [comment]
Curious what was the issue at the end

**Comment by josejbarneto** [comment]
Seems like the token was giving me access to the wrong page, i'd got a new want and it worked,

btw, ¿how can u publish different messages depending on what social network im posting?

**Comment by martin-georgiev** [comment]
E.g. for Twitter should be something along these lines:
```
$post = 'Message for Twitter';
$message = new Message($post);
$message->setNetworksToPublishOn([SocialNetwork::TWITTER]);
$container->get('social_post')->publish($message);
```

and for Facebook:

```
$post = 'Message for Facebook';
$message = new Message($post);
$message->setNetworksToPublishOn([SocialNetwork::FACEBOOK]);
$container->get('social_post')->publish($message);
```

**Comment by josejbarneto** [comment]
Thank you very much, great tool and you answer time is great

**Comment by martin-georgiev** [comment]
You're welcome.

**Comment by hajlaaoui** [comment]
Bonjour, j'utilise votre bundle pour publier sur Twitter et Facebook, Twitter fonctionne correctement, mais lorsque j'essaie de publier sur fb, j'obtiens cette erreu
Attempted to call an undefined method named "publish" of class
